### ISSUE TITLE
Unchecked runtime.lastError: QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by SanderLam** [KeesCBakker/databricks-power-tools#6]
Hi there!

Thanks for an awesome add-on! 
I've been working on my own theme (which I of course would like to share later on), but I'm getting this error when my CSS code get's bigger than 8KB:

![image](https://user-images.githubusercontent.com/43031019/113263994-c15fca80-92d2-11eb-82b8-976ce1c1f50f.png)

After some investigation, I found that this is an option in the `chrome.storage` API:
https://developer.chrome.com/docs/extensions/reference/storage/

Therefore my question would be if it is possible to extend this to accept bigger files, which would I think be a change in the `save_options`-function in `databricks-power-tools/app/options/options.js`.
I'm not an expert in JavaScript in any way, so I wouldn't dare to make that change myself though ;)

Best,
Sander

**Comment by KeesCBakker** [comment]
That is one big stylesheet you're working on. What happens if you minify it?

Right now I'm storing text blobs. Let me check what I can do.
